# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']

Options:
  test-before-installing: True
  require-passing-tests-on: ['Linux/Q5', 'FreeBSD/Qt5']
