export QTDIR = /usr/share/qt3
#############################################################################
# Makefile for building: stopmotion
# Generated by qmake (1.07a) (Qt 3.3.4) on: Sun Sep  4 23:23:45 2005
# Project:  stopmotion.pro
# Template: app
# Command: $(QMAKE) "QMAKE_CXXFLAGS=-pipe -DNO_DEBUG" -o Makefile stopmotion.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -DNO_DEBUG -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -Isrc -Isrc/presentation/frontends/qtfrontend -Isrc/presentation/frontends/nonguifrontend -Isrc/foundation -Isrc/domain -Isrc/domain/animation -Isrc/presentation -I/usr/include/SDL -I-D_REENTRANT -I/usr/include/libxml2 -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -L/usr/lib -lSDL -lpthread -lxml2 -lz -lSDL_image -ltar -lvorbis -lvorbisfile -lfam -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = src/config.h \
		src/domain/domainfacade.h \
		src/foundation/logger.h \
		src/presentation/observer.h \
		src/domain/animation/animation.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/nonguifrontend/nonguifrontend.h \
		src/presentation/frontends/qtfrontend/mainwindowgui.h \
		src/presentation/frontends/qtfrontend/qtfrontend.h \
		src/application/runanimationhandler.h \
		src/presentation/frontends/qtfrontend/picturepreview.h \
		src/domain/undo/undo.h \
		src/domain/undo/undoadd.h \
		src/domain/undo/undomove.h \
		src/domain/undo/undoremove.h \
		src/application/camerahandler.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/domain/undo/undohistory.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/presentation/frontends/qtfrontend/flexiblelineedit.h \
		src/presentation/frontends/frontend.h \
		stopmotion.desktop \
		stopmotion.mime \
		graphics/stopmotion.png \
		graphics/icons/addframeicon.xpm \
		graphics/icons/cameraoff.xpm \
		graphics/icons/cameraon.xpm \
		graphics/icons/capture.xpm \
		graphics/icons/clapper.xpm \
		graphics/icons/closescene.xpm \
		graphics/icons/close.xpm \
		graphics/icons/configureicon.xpm \
		graphics/icons/copyicon.xpm \
		graphics/icons/cuticon.xpm \
		graphics/icons/fastforward.xpm \
		graphics/icons/filenewicon.xpm \
		graphics/icons/fileopenicon.xpm \
		graphics/icons/filesaveasicon.xpm \
		graphics/icons/filesaveicon.xpm \
		graphics/icons/home.xpm \
		graphics/icons/languages.xpm \
		graphics/icons/loop.xpm \
		graphics/icons/newscene.xpm \
		graphics/icons/nextframe.xpm \
		graphics/icons/note.xpm \
		graphics/icons/openscene.xpm \
		graphics/icons/pasteicon.xpm \
		graphics/icons/pause.xpm \
		graphics/icons/play.xpm \
		graphics/icons/previousframe.xpm \
		graphics/icons/quiticon.xpm \
		graphics/icons/redoicon.xpm \
		graphics/icons/removeframeicon.xpm \
		graphics/icons/removescene.xpm \
		graphics/icons/rewind.xpm \
		graphics/icons/steptobeginning.xpm \
		graphics/icons/steptoend.xpm \
		graphics/icons/stop.xpm \
		graphics/icons/undoicon.xpm \
		graphics/icons/videoexport.xpm \
		graphics/icons/whatsthisicon.xpm \
		graphics/icons/windowicon.xpm \
		src/presentation/frontends/qtfrontend/filedialog.h \
		src/application/soundhandler.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/application/editmenuhandler.h \
		src/domain/animation/scene.h \
		src/technical/projectserializer.h \
		src/technical/packer.h \
		src/presentation/frontends/qtfrontend/licence.h \
		src/technical/audio/audiodriver.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/ossdriver.h \
		src/technical/audio/oggvorbis.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/technical/grabber/commandlinegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/presentation/frontends/qtfrontend/preferencesmenu.h \
		src/foundation/preferencestool.h \
		src/application/modelhandler.h \
		src/domain/undo/undonewscene.h \
		src/domain/undo/undoremovescene.h \
		src/domain/undo/undomovescene.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/application/languagehandler.h \
		src/technical/video/videofactory.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/importtab.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/presentation/frontends/qtfrontend/framebar/framethumbview.h \
		src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.h \
		src/presentation/frontends/qtfrontend/framebar/scenethumbview.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/exporttab.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/helpwindow.h
SOURCES = src/main.cpp \
		src/domain/domainfacade.cpp \
		src/foundation/logger.cpp \
		src/domain/animation/animation.cpp \
		src/domain/animation/animationmodel.cpp \
		src/domain/animation/frame.cpp \
		src/presentation/frontends/nonguifrontend/nonguifrontend.cpp \
		src/presentation/frontends/qtfrontend/mainwindowgui.cpp \
		src/presentation/frontends/qtfrontend/qtfrontend.cpp \
		src/application/runanimationhandler.cpp \
		src/presentation/frontends/qtfrontend/picturepreview.cpp \
		src/domain/undo/undoadd.cpp \
		src/domain/undo/undomove.cpp \
		src/domain/undo/undoremove.cpp \
		src/application/camerahandler.cpp \
		src/presentation/frontends/qtfrontend/frameview.cpp \
		src/domain/undo/undohistory.cpp \
		src/presentation/frontends/qtfrontend/flexiblespinbox.cpp \
		src/presentation/frontends/qtfrontend/menuframe.cpp \
		src/presentation/frontends/qtfrontend/flexiblelineedit.cpp \
		src/presentation/frontends/qtfrontend/filedialog.cpp \
		src/application/soundhandler.cpp \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.cpp \
		src/application/editmenuhandler.cpp \
		src/domain/animation/scene.cpp \
		src/technical/projectserializer.cpp \
		src/technical/packer.c \
		src/technical/audio/ossdriver.cpp \
		src/technical/audio/oggvorbis.cpp \
		src/presentation/frontends/qtfrontend/videoview.cpp \
		src/technical/grabber/imagegrabber.cpp \
		src/technical/grabber/commandlinegrabber.cpp \
		src/presentation/frontends/qtfrontend/imagegrabthread.cpp \
		src/presentation/frontends/qtfrontend/preferencesmenu.cpp \
		src/foundation/preferencestool.cpp \
		src/application/modelhandler.cpp \
		src/domain/undo/undonewscene.cpp \
		src/domain/undo/undoremovescene.cpp \
		src/domain/undo/undomovescene.cpp \
		src/presentation/frontends/qtfrontend/toolsmenu.cpp \
		src/application/languagehandler.cpp \
		src/technical/video/videofactory.cpp \
		src/technical/video/videoencoder.cpp \
		src/presentation/frontends/qtfrontend/importtab.cpp \
		src/presentation/frontends/qtfrontend/framebar/framebar.cpp \
		src/presentation/frontends/qtfrontend/framebar/framethumbview.cpp \
		src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.cpp \
		src/presentation/frontends/qtfrontend/framebar/scenethumbview.cpp \
		src/presentation/frontends/qtfrontend/framebar/thumbview.cpp \
		src/presentation/frontends/qtfrontend/exporttab.cpp \
		src/application/externalchangemonitor.cpp \
		src/presentation/frontends/qtfrontend/helpwindow.cpp
OBJECTS = main.o \
		domainfacade.o \
		logger.o \
		animation.o \
		animationmodel.o \
		frame.o \
		nonguifrontend.o \
		mainwindowgui.o \
		qtfrontend.o \
		runanimationhandler.o \
		picturepreview.o \
		undoadd.o \
		undomove.o \
		undoremove.o \
		camerahandler.o \
		frameview.o \
		undohistory.o \
		flexiblespinbox.o \
		menuframe.o \
		flexiblelineedit.o \
		filedialog.o \
		soundhandler.o \
		framepreferencesmenu.o \
		editmenuhandler.o \
		scene.o \
		projectserializer.o \
		packer.o \
		ossdriver.o \
		oggvorbis.o \
		videoview.o \
		imagegrabber.o \
		commandlinegrabber.o \
		imagegrabthread.o \
		preferencesmenu.o \
		preferencestool.o \
		modelhandler.o \
		undonewscene.o \
		undoremovescene.o \
		undomovescene.o \
		toolsmenu.o \
		languagehandler.o \
		videofactory.o \
		videoencoder.o \
		importtab.o \
		framebar.o \
		framethumbview.o \
		scenearrowbutton.o \
		scenethumbview.o \
		thumbview.o \
		exporttab.o \
		externalchangemonitor.o \
		helpwindow.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = src/presentation/frontends/qtfrontend/moc_mainwindowgui.cpp \
		src/presentation/frontends/qtfrontend/moc_qtfrontend.cpp \
		src/application/moc_runanimationhandler.cpp \
		src/application/moc_camerahandler.cpp \
		src/presentation/frontends/qtfrontend/moc_frameview.cpp \
		src/presentation/frontends/qtfrontend/moc_flexiblespinbox.cpp \
		src/presentation/frontends/qtfrontend/moc_menuframe.cpp \
		src/presentation/frontends/qtfrontend/moc_flexiblelineedit.cpp \
		src/presentation/frontends/qtfrontend/moc_filedialog.cpp \
		src/application/moc_soundhandler.cpp \
		src/presentation/frontends/qtfrontend/moc_framepreferencesmenu.cpp \
		src/application/moc_editmenuhandler.cpp \
		src/presentation/frontends/qtfrontend/moc_videoview.cpp \
		src/presentation/frontends/qtfrontend/moc_preferencesmenu.cpp \
		src/application/moc_modelhandler.cpp \
		src/presentation/frontends/qtfrontend/moc_toolsmenu.cpp \
		src/application/moc_languagehandler.cpp \
		src/presentation/frontends/qtfrontend/moc_importtab.cpp \
		src/presentation/frontends/qtfrontend/framebar/moc_framebar.cpp \
		src/presentation/frontends/qtfrontend/framebar/moc_scenearrowbutton.cpp \
		src/presentation/frontends/qtfrontend/framebar/moc_scenethumbview.cpp \
		src/presentation/frontends/qtfrontend/moc_exporttab.cpp \
		src/application/moc_externalchangemonitor.cpp \
		src/presentation/frontends/qtfrontend/moc_helpwindow.cpp
OBJMOC = moc_mainwindowgui.o \
		moc_qtfrontend.o \
		moc_runanimationhandler.o \
		moc_camerahandler.o \
		moc_frameview.o \
		moc_flexiblespinbox.o \
		moc_menuframe.o \
		moc_flexiblelineedit.o \
		moc_filedialog.o \
		moc_soundhandler.o \
		moc_framepreferencesmenu.o \
		moc_editmenuhandler.o \
		moc_videoview.o \
		moc_preferencesmenu.o \
		moc_modelhandler.o \
		moc_toolsmenu.o \
		moc_languagehandler.o \
		moc_importtab.o \
		moc_framebar.o \
		moc_scenearrowbutton.o \
		moc_scenethumbview.o \
		moc_exporttab.o \
		moc_externalchangemonitor.o \
		moc_helpwindow.o
DIST	   = conf.pri \
		stopmotion.pro
QMAKE_TARGET = stopmotion
DESTDIR  = 
TARGET   = stopmotion

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: stopmotion.pro  /usr/share/qt3/mkspecs/default/qmake.conf conf.pri \
		/usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) "QMAKE_CXXFLAGS=-pipe -DNO_DEBUG" -o Makefile stopmotion.pro
qmake: 
	@$(QMAKE) "QMAKE_CXXFLAGS=-pipe -DNO_DEBUG" -o Makefile stopmotion.pro

dist: 
	@mkdir -p .tmp/stopmotion && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/stopmotion/ && $(COPY_FILE) --parents translations/stopmotion_no_nb.ts translations/stopmotion_no_nn.ts translations/stopmotion_no_se.ts translations/stopmotion_de.ts translations/stopmotion_se.ts translations/stopmotion_fr.ts translations/stopmotion_br.ts translations/stopmotion_dk.ts translations/stopmotion_fi.ts translations/stopmotion_gr.ts translations/stopmotion_ru.ts translations/stopmotion_es.ts translations/stopmotion_kl.ts .tmp/stopmotion/ && ( cd `dirname .tmp/stopmotion` && $(TAR) stopmotion.tar stopmotion && $(GZIP) stopmotion.tar ) && $(MOVE) `dirname .tmp/stopmotion`/stopmotion.tar.gz . && $(DEL_FILE) -r .tmp/stopmotion

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: src/main.cpp src/config.h \
		src/domain/domainfacade.h \
		src/presentation/frontends/qtfrontend/qtfrontend.h \
		src/presentation/frontends/nonguifrontend/nonguifrontend.h \
		src/foundation/preferencestool.h \
		src/foundation/logger.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/domain/undo/undo.h \
		src/presentation/frontends/qtfrontend/mainwindowgui.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/application/camerahandler.h \
		src/application/editmenuhandler.h \
		src/application/runanimationhandler.h \
		src/application/modelhandler.h \
		src/application/languagehandler.h \
		src/application/soundhandler.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

domainfacade.o: src/domain/domainfacade.cpp src/domain/domainfacade.h \
		src/domain/animation/animation.h \
		src/foundation/logger.h \
		src/domain/undo/undoadd.h \
		src/domain/undo/undomove.h \
		src/domain/undo/undoremove.h \
		src/domain/undo/undonewscene.h \
		src/domain/undo/undoremovescene.h \
		src/domain/undo/undomovescene.h \
		src/config.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/domain/undo/undo.h \
		src/domain/animation/scene.h \
		src/technical/projectserializer.h \
		src/technical/audio/ossdriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o domainfacade.o src/domain/domainfacade.cpp

logger.o: src/foundation/logger.cpp src/foundation/logger.h \
		src/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o src/foundation/logger.cpp

animation.o: src/domain/animation/animation.cpp src/domain/animation/animation.h \
		src/foundation/logger.h \
		src/technical/audio/ossdriver.h \
		src/technical/video/videofactory.h \
		src/config.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/scene.h \
		src/technical/projectserializer.h \
		src/domain/animation/frame.h \
		src/presentation/observer.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animation.o src/domain/animation/animation.cpp

animationmodel.o: src/domain/animation/animationmodel.cpp src/domain/animation/animationmodel.h \
		src/foundation/logger.h \
		src/config.h \
		src/presentation/observer.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/domain/animation/frame.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animationmodel.o src/domain/animation/animationmodel.cpp

frame.o: src/domain/animation/frame.cpp src/domain/animation/frame.h \
		src/technical/audio/oggvorbis.h \
		src/config.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/foundation/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frame.o src/domain/animation/frame.cpp

nonguifrontend.o: src/presentation/frontends/nonguifrontend/nonguifrontend.cpp src/presentation/frontends/nonguifrontend/nonguifrontend.h \
		src/config.h \
		src/presentation/frontends/frontend.h \
		src/domain/domainfacade.h \
		src/foundation/logger.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/technical/video/videoencoder.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nonguifrontend.o src/presentation/frontends/nonguifrontend/nonguifrontend.cpp

mainwindowgui.o: src/presentation/frontends/qtfrontend/mainwindowgui.cpp src/presentation/frontends/qtfrontend/mainwindowgui.h \
		src/domain/domainfacade.h \
		src/foundation/preferencestool.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/presentation/frontends/qtfrontend/flexiblelineedit.h \
		src/presentation/frontends/qtfrontend/licence.h \
		src/presentation/frontends/qtfrontend/preferencesmenu.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		graphics/icons/windowicon.xpm \
		graphics/icons/configureicon.xpm \
		graphics/icons/undoicon.xpm \
		graphics/icons/redoicon.xpm \
		graphics/icons/cuticon.xpm \
		graphics/icons/copyicon.xpm \
		graphics/icons/pasteicon.xpm \
		graphics/icons/filenewicon.xpm \
		graphics/icons/fileopenicon.xpm \
		graphics/icons/filesaveicon.xpm \
		graphics/icons/filesaveasicon.xpm \
		graphics/icons/quiticon.xpm \
		graphics/icons/whatsthisicon.xpm \
		graphics/icons/close.xpm \
		graphics/icons/videoexport.xpm \
		graphics/icons/languages.xpm \
		src/presentation/frontends/qtfrontend/helpwindow.h \
		src/config.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/application/camerahandler.h \
		src/application/editmenuhandler.h \
		src/application/runanimationhandler.h \
		src/application/modelhandler.h \
		src/application/languagehandler.h \
		src/application/soundhandler.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/foundation/logger.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h \
		src/presentation/frontends/qtfrontend/importtab.h \
		src/presentation/frontends/qtfrontend/exporttab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindowgui.o src/presentation/frontends/qtfrontend/mainwindowgui.cpp

qtfrontend.o: src/presentation/frontends/qtfrontend/qtfrontend.cpp src/presentation/frontends/qtfrontend/qtfrontend.h \
		src/foundation/preferencestool.h \
		src/config.h \
		src/presentation/frontends/frontend.h \
		src/presentation/frontends/qtfrontend/mainwindowgui.h \
		src/foundation/logger.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/application/camerahandler.h \
		src/application/editmenuhandler.h \
		src/application/runanimationhandler.h \
		src/application/modelhandler.h \
		src/application/languagehandler.h \
		src/application/soundhandler.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/domainfacade.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtfrontend.o src/presentation/frontends/qtfrontend/qtfrontend.cpp

runanimationhandler.o: src/application/runanimationhandler.cpp src/application/runanimationhandler.h \
		src/foundation/preferencestool.h \
		src/domain/domainfacade.h \
		src/config.h \
		src/foundation/logger.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o runanimationhandler.o src/application/runanimationhandler.cpp

picturepreview.o: src/presentation/frontends/qtfrontend/picturepreview.cpp src/presentation/frontends/qtfrontend/picturepreview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o picturepreview.o src/presentation/frontends/qtfrontend/picturepreview.cpp

undoadd.o: src/domain/undo/undoadd.cpp src/domain/undo/undoadd.h \
		src/domain/undo/undo.h \
		src/domain/animation/animationmodel.h \
		src/config.h \
		src/presentation/observer.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/domain/animation/frame.h \
		src/foundation/logger.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o undoadd.o src/domain/undo/undoadd.cpp

undomove.o: src/domain/undo/undomove.cpp src/domain/undo/undomove.h \
		src/domain/undo/undo.h \
		src/domain/animation/animationmodel.h \
		src/config.h \
		src/presentation/observer.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/domain/animation/frame.h \
		src/foundation/logger.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o undomove.o src/domain/undo/undomove.cpp

undoremove.o: src/domain/undo/undoremove.cpp src/domain/undo/undoremove.h \
		src/domain/undo/undo.h \
		src/domain/animation/animationmodel.h \
		src/config.h \
		src/presentation/observer.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/domain/animation/frame.h \
		src/foundation/logger.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o undoremove.o src/domain/undo/undoremove.cpp

camerahandler.o: src/application/camerahandler.cpp src/application/camerahandler.h \
		src/domain/domainfacade.h \
		src/foundation/preferencestool.h \
		graphics/icons/cameraoff.xpm \
		graphics/icons/cameraon.xpm \
		src/config.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/application/modelhandler.h \
		src/foundation/logger.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/technical/video/videoencoder.h \
		src/domain/undo/undo.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camerahandler.o src/application/camerahandler.cpp

frameview.o: src/presentation/frontends/qtfrontend/frameview.cpp src/presentation/frontends/qtfrontend/frameview.h \
		src/technical/grabber/commandlinegrabber.h \
		src/foundation/preferencestool.h \
		src/config.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/domainfacade.h \
		src/foundation/logger.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/technical/video/videoencoder.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frameview.o src/presentation/frontends/qtfrontend/frameview.cpp

undohistory.o: src/domain/undo/undohistory.cpp src/domain/undo/undohistory.h \
		src/domain/undo/undo.h \
		src/domain/animation/animationmodel.h \
		src/config.h \
		src/presentation/observer.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/domain/animation/frame.h \
		src/foundation/logger.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o undohistory.o src/domain/undo/undohistory.cpp

flexiblespinbox.o: src/presentation/frontends/qtfrontend/flexiblespinbox.cpp src/presentation/frontends/qtfrontend/flexiblespinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flexiblespinbox.o src/presentation/frontends/qtfrontend/flexiblespinbox.cpp

menuframe.o: src/presentation/frontends/qtfrontend/menuframe.cpp src/presentation/frontends/qtfrontend/menuframe.h \
		src/presentation/frontends/qtfrontend/mainwindowgui.h \
		src/config.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/application/camerahandler.h \
		src/application/editmenuhandler.h \
		src/application/runanimationhandler.h \
		src/application/modelhandler.h \
		src/application/languagehandler.h \
		src/application/soundhandler.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/foundation/logger.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/domainfacade.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menuframe.o src/presentation/frontends/qtfrontend/menuframe.cpp

flexiblelineedit.o: src/presentation/frontends/qtfrontend/flexiblelineedit.cpp src/presentation/frontends/qtfrontend/flexiblelineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flexiblelineedit.o src/presentation/frontends/qtfrontend/flexiblelineedit.cpp

filedialog.o: src/presentation/frontends/qtfrontend/filedialog.cpp src/presentation/frontends/qtfrontend/filedialog.h \
		graphics/icons/home.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filedialog.o src/presentation/frontends/qtfrontend/filedialog.cpp

soundhandler.o: src/application/soundhandler.cpp src/application/soundhandler.h \
		src/domain/domainfacade.h \
		src/config.h \
		src/foundation/logger.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundhandler.o src/application/soundhandler.cpp

framepreferencesmenu.o: src/presentation/frontends/qtfrontend/framepreferencesmenu.cpp src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/domain/domainfacade.h \
		graphics/icons/close.xpm \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h \
		src/config.h \
		src/foundation/logger.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o framepreferencesmenu.o src/presentation/frontends/qtfrontend/framepreferencesmenu.cpp

editmenuhandler.o: src/application/editmenuhandler.cpp src/application/editmenuhandler.h \
		src/domain/domainfacade.h \
		src/presentation/frontends/qtfrontend/mainwindowgui.h \
		src/config.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/application/modelhandler.h \
		src/foundation/logger.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/application/soundhandler.h \
		src/application/externalchangemonitor.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/application/camerahandler.h \
		src/application/runanimationhandler.h \
		src/application/languagehandler.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editmenuhandler.o src/application/editmenuhandler.cpp

scene.o: src/domain/animation/scene.cpp src/domain/animation/scene.h \
		src/config.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/frontend.h \
		src/foundation/logger.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scene.o src/domain/animation/scene.cpp

projectserializer.o: src/technical/projectserializer.cpp src/technical/projectserializer.h \
		src/foundation/logger.h \
		src/technical/packer.h \
		src/domain/animation/frame.h \
		src/domain/animation/scene.h \
		src/presentation/frontends/frontend.h \
		src/config.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectserializer.o src/technical/projectserializer.cpp

packer.o: src/technical/packer.c src/technical/packer.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o packer.o src/technical/packer.c

ossdriver.o: src/technical/audio/ossdriver.cpp src/technical/audio/ossdriver.h \
		src/foundation/logger.h \
		src/technical/audio/audiodriver.h \
		src/technical/audio/audioformat.h \
		src/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ossdriver.o src/technical/audio/ossdriver.cpp

oggvorbis.o: src/technical/audio/oggvorbis.cpp src/technical/audio/oggvorbis.h \
		src/foundation/logger.h \
		src/technical/audio/audioformat.h \
		src/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oggvorbis.o src/technical/audio/oggvorbis.cpp

videoview.o: src/presentation/frontends/qtfrontend/videoview.cpp src/presentation/frontends/qtfrontend/videoview.h \
		src/config.h \
		src/presentation/observer.h \
		src/foundation/logger.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videoview.o src/presentation/frontends/qtfrontend/videoview.cpp

imagegrabber.o: src/technical/grabber/imagegrabber.cpp src/technical/grabber/imagegrabber.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagegrabber.o src/technical/grabber/imagegrabber.cpp

commandlinegrabber.o: src/technical/grabber/commandlinegrabber.cpp src/technical/grabber/commandlinegrabber.h \
		src/config.h \
		src/technical/grabber/imagegrabber.h \
		src/foundation/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commandlinegrabber.o src/technical/grabber/commandlinegrabber.cpp

imagegrabthread.o: src/presentation/frontends/qtfrontend/imagegrabthread.cpp src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/technical/grabber/imagegrabber.h \
		src/config.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/domain/domainfacade.h \
		src/foundation/logger.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/technical/video/videoencoder.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagegrabthread.o src/presentation/frontends/qtfrontend/imagegrabthread.cpp

preferencesmenu.o: src/presentation/frontends/qtfrontend/preferencesmenu.cpp src/presentation/frontends/qtfrontend/preferencesmenu.h \
		src/foundation/preferencestool.h \
		src/presentation/frontends/qtfrontend/flexiblelineedit.h \
		src/presentation/frontends/qtfrontend/importtab.h \
		src/presentation/frontends/qtfrontend/exporttab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferencesmenu.o src/presentation/frontends/qtfrontend/preferencesmenu.cpp

preferencestool.o: src/foundation/preferencestool.cpp src/foundation/preferencestool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferencestool.o src/foundation/preferencestool.cpp

modelhandler.o: src/application/modelhandler.cpp src/application/modelhandler.h \
		src/presentation/frontends/qtfrontend/mainwindowgui.h \
		src/domain/domainfacade.h \
		src/presentation/frontends/qtfrontend/filedialog.h \
		src/presentation/frontends/qtfrontend/picturepreview.h \
		src/config.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/application/externalchangemonitor.h \
		src/foundation/logger.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/application/camerahandler.h \
		src/application/editmenuhandler.h \
		src/application/runanimationhandler.h \
		src/application/languagehandler.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modelhandler.o src/application/modelhandler.cpp

undonewscene.o: src/domain/undo/undonewscene.cpp src/domain/undo/undonewscene.h \
		src/domain/undo/undo.h \
		src/domain/animation/animationmodel.h \
		src/config.h \
		src/presentation/observer.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/domain/animation/frame.h \
		src/foundation/logger.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o undonewscene.o src/domain/undo/undonewscene.cpp

undoremovescene.o: src/domain/undo/undoremovescene.cpp src/domain/undo/undoremovescene.h \
		src/domain/undo/undo.h \
		src/domain/animation/animationmodel.h \
		src/config.h \
		src/presentation/observer.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/domain/animation/frame.h \
		src/foundation/logger.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o undoremovescene.o src/domain/undo/undoremovescene.cpp

undomovescene.o: src/domain/undo/undomovescene.cpp src/domain/undo/undomovescene.h \
		src/domain/undo/undo.h \
		src/domain/animation/animationmodel.h \
		src/config.h \
		src/presentation/observer.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/domain/animation/frame.h \
		src/foundation/logger.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o undomovescene.o src/domain/undo/undomovescene.cpp

toolsmenu.o: src/presentation/frontends/qtfrontend/toolsmenu.cpp src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/foundation/preferencestool.h \
		graphics/icons/play.xpm \
		graphics/icons/fastforward.xpm \
		graphics/icons/rewind.xpm \
		graphics/icons/steptoend.xpm \
		graphics/icons/steptobeginning.xpm \
		graphics/icons/stop.xpm \
		graphics/icons/pause.xpm \
		graphics/icons/loop.xpm \
		graphics/icons/capture.xpm \
		graphics/icons/cameraon.xpm \
		graphics/icons/addframeicon.xpm \
		graphics/icons/removeframeicon.xpm \
		graphics/icons/newscene.xpm \
		graphics/icons/removescene.xpm \
		src/application/runanimationhandler.h \
		src/application/modelhandler.h \
		src/application/camerahandler.h \
		src/config.h \
		src/foundation/logger.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/application/externalchangemonitor.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/domainfacade.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolsmenu.o src/presentation/frontends/qtfrontend/toolsmenu.cpp

languagehandler.o: src/application/languagehandler.cpp src/application/languagehandler.h \
		src/foundation/preferencestool.h \
		src/config.h \
		src/foundation/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o languagehandler.o src/application/languagehandler.cpp

videofactory.o: src/technical/video/videofactory.cpp src/technical/video/videofactory.h \
		src/technical/video/videoencoder.h \
		src/technical/projectserializer.h \
		src/presentation/frontends/frontend.h \
		src/domain/animation/scene.h \
		src/config.h \
		src/domain/animation/frame.h \
		src/foundation/logger.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videofactory.o src/technical/video/videofactory.cpp

videoencoder.o: src/technical/video/videoencoder.cpp src/technical/video/videoencoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videoencoder.o src/technical/video/videoencoder.cpp

importtab.o: src/presentation/frontends/qtfrontend/importtab.cpp src/presentation/frontends/qtfrontend/importtab.h \
		src/foundation/preferencestool.h \
		src/presentation/frontends/qtfrontend/flexiblelineedit.h \
		graphics/icons/close.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o importtab.o src/presentation/frontends/qtfrontend/importtab.cpp

framebar.o: src/presentation/frontends/qtfrontend/framebar/framebar.cpp src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/domain/domainfacade.h \
		src/presentation/frontends/qtfrontend/framebar/framethumbview.h \
		src/presentation/frontends/qtfrontend/framebar/scenethumbview.h \
		src/config.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/foundation/logger.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h \
		src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o framebar.o src/presentation/frontends/qtfrontend/framebar/framebar.cpp

framethumbview.o: src/presentation/frontends/qtfrontend/framebar/framethumbview.cpp src/presentation/frontends/qtfrontend/framebar/framethumbview.h \
		src/domain/domainfacade.h \
		src/presentation/frontends/qtfrontend/mainwindowgui.h \
		graphics/icons/note.xpm \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/config.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/foundation/logger.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/application/camerahandler.h \
		src/application/editmenuhandler.h \
		src/application/runanimationhandler.h \
		src/application/modelhandler.h \
		src/application/languagehandler.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o framethumbview.o src/presentation/frontends/qtfrontend/framebar/framethumbview.cpp

scenearrowbutton.o: src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.cpp src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.h \
		graphics/icons/openscene.xpm \
		graphics/icons/closescene.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scenearrowbutton.o src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.cpp

scenethumbview.o: src/presentation/frontends/qtfrontend/framebar/scenethumbview.cpp src/presentation/frontends/qtfrontend/framebar/scenethumbview.h \
		graphics/icons/clapper.xpm \
		src/domain/domainfacade.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/config.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/foundation/logger.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scenethumbview.o src/presentation/frontends/qtfrontend/framebar/scenethumbview.cpp

thumbview.o: src/presentation/frontends/qtfrontend/framebar/thumbview.cpp src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/domain/domainfacade.h \
		src/presentation/frontends/qtfrontend/mainwindowgui.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/config.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/foundation/logger.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/application/camerahandler.h \
		src/application/editmenuhandler.h \
		src/application/runanimationhandler.h \
		src/application/modelhandler.h \
		src/application/languagehandler.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thumbview.o src/presentation/frontends/qtfrontend/framebar/thumbview.cpp

exporttab.o: src/presentation/frontends/qtfrontend/exporttab.cpp src/presentation/frontends/qtfrontend/exporttab.h \
		graphics/icons/close.xpm \
		src/presentation/frontends/qtfrontend/flexiblelineedit.h \
		src/foundation/preferencestool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exporttab.o src/presentation/frontends/qtfrontend/exporttab.cpp

externalchangemonitor.o: src/application/externalchangemonitor.cpp src/application/externalchangemonitor.h \
		src/domain/domainfacade.h \
		src/config.h \
		src/foundation/logger.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/presentation/frontends/frontend.h \
		src/technical/video/videoencoder.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o externalchangemonitor.o src/application/externalchangemonitor.cpp

helpwindow.o: src/presentation/frontends/qtfrontend/helpwindow.cpp src/presentation/frontends/qtfrontend/helpwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpwindow.o src/presentation/frontends/qtfrontend/helpwindow.cpp

moc_mainwindowgui.o: src/presentation/frontends/qtfrontend/moc_mainwindowgui.cpp  src/presentation/frontends/qtfrontend/mainwindowgui.h src/config.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/application/camerahandler.h \
		src/application/editmenuhandler.h \
		src/application/runanimationhandler.h \
		src/application/modelhandler.h \
		src/application/languagehandler.h \
		src/application/soundhandler.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/foundation/logger.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/domainfacade.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindowgui.o src/presentation/frontends/qtfrontend/moc_mainwindowgui.cpp

moc_qtfrontend.o: src/presentation/frontends/qtfrontend/moc_qtfrontend.cpp  src/presentation/frontends/qtfrontend/qtfrontend.h src/config.h \
		src/presentation/frontends/frontend.h \
		src/presentation/frontends/qtfrontend/mainwindowgui.h \
		src/foundation/logger.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/presentation/frontends/qtfrontend/flexiblespinbox.h \
		src/application/camerahandler.h \
		src/application/editmenuhandler.h \
		src/application/runanimationhandler.h \
		src/application/modelhandler.h \
		src/application/languagehandler.h \
		src/application/soundhandler.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/qtfrontend/toolsmenu.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/domainfacade.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtfrontend.o src/presentation/frontends/qtfrontend/moc_qtfrontend.cpp

moc_runanimationhandler.o: src/application/moc_runanimationhandler.cpp  src/application/runanimationhandler.h src/config.h \
		src/foundation/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_runanimationhandler.o src/application/moc_runanimationhandler.cpp

moc_camerahandler.o: src/application/moc_camerahandler.cpp  src/application/camerahandler.h src/config.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/application/modelhandler.h \
		src/foundation/logger.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/domainfacade.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/technical/video/videoencoder.h \
		src/domain/undo/undo.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/application/externalchangemonitor.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camerahandler.o src/application/moc_camerahandler.cpp

moc_frameview.o: src/presentation/frontends/qtfrontend/moc_frameview.cpp  src/presentation/frontends/qtfrontend/frameview.h src/config.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/observer.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/domainfacade.h \
		src/foundation/logger.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/domain/animation/animationmodel.h \
		src/domain/undo/undohistory.h \
		src/technical/video/videoencoder.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frameview.o src/presentation/frontends/qtfrontend/moc_frameview.cpp

moc_flexiblespinbox.o: src/presentation/frontends/qtfrontend/moc_flexiblespinbox.cpp  src/presentation/frontends/qtfrontend/flexiblespinbox.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_flexiblespinbox.o src/presentation/frontends/qtfrontend/moc_flexiblespinbox.cpp

moc_menuframe.o: src/presentation/frontends/qtfrontend/moc_menuframe.cpp  src/presentation/frontends/qtfrontend/menuframe.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menuframe.o src/presentation/frontends/qtfrontend/moc_menuframe.cpp

moc_flexiblelineedit.o: src/presentation/frontends/qtfrontend/moc_flexiblelineedit.cpp  src/presentation/frontends/qtfrontend/flexiblelineedit.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_flexiblelineedit.o src/presentation/frontends/qtfrontend/moc_flexiblelineedit.cpp

moc_filedialog.o: src/presentation/frontends/qtfrontend/moc_filedialog.cpp  src/presentation/frontends/qtfrontend/filedialog.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filedialog.o src/presentation/frontends/qtfrontend/moc_filedialog.cpp

moc_soundhandler.o: src/application/moc_soundhandler.cpp  src/application/soundhandler.h src/config.h \
		src/foundation/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundhandler.o src/application/moc_soundhandler.cpp

moc_framepreferencesmenu.o: src/presentation/frontends/qtfrontend/moc_framepreferencesmenu.cpp  src/presentation/frontends/qtfrontend/framepreferencesmenu.h src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h \
		src/config.h \
		src/foundation/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_framepreferencesmenu.o src/presentation/frontends/qtfrontend/moc_framepreferencesmenu.cpp

moc_editmenuhandler.o: src/application/moc_editmenuhandler.cpp  src/application/editmenuhandler.h src/config.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/application/modelhandler.h \
		src/foundation/logger.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/application/soundhandler.h \
		src/application/externalchangemonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editmenuhandler.o src/application/moc_editmenuhandler.cpp

moc_videoview.o: src/presentation/frontends/qtfrontend/moc_videoview.cpp  src/presentation/frontends/qtfrontend/videoview.h src/config.h \
		src/presentation/observer.h \
		src/foundation/logger.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videoview.o src/presentation/frontends/qtfrontend/moc_videoview.cpp

moc_preferencesmenu.o: src/presentation/frontends/qtfrontend/moc_preferencesmenu.cpp  src/presentation/frontends/qtfrontend/preferencesmenu.h src/presentation/frontends/qtfrontend/importtab.h \
		src/presentation/frontends/qtfrontend/exporttab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferencesmenu.o src/presentation/frontends/qtfrontend/moc_preferencesmenu.cpp

moc_modelhandler.o: src/application/moc_modelhandler.cpp  src/application/modelhandler.h src/config.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/application/externalchangemonitor.h \
		src/foundation/logger.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modelhandler.o src/application/moc_modelhandler.cpp

moc_toolsmenu.o: src/presentation/frontends/qtfrontend/moc_toolsmenu.cpp  src/presentation/frontends/qtfrontend/toolsmenu.h src/application/runanimationhandler.h \
		src/application/modelhandler.h \
		src/application/camerahandler.h \
		src/config.h \
		src/foundation/logger.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/application/externalchangemonitor.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h \
		src/presentation/frontends/qtfrontend/videoview.h \
		src/presentation/frontends/qtfrontend/frameview.h \
		src/technical/grabber/imagegrabber.h \
		src/presentation/frontends/qtfrontend/imagegrabthread.h \
		src/domain/domainfacade.h \
		src/domain/undo/undohistory.h \
		src/domain/undo/undo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolsmenu.o src/presentation/frontends/qtfrontend/moc_toolsmenu.cpp

moc_languagehandler.o: src/application/moc_languagehandler.cpp  src/application/languagehandler.h src/config.h \
		src/foundation/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_languagehandler.o src/application/moc_languagehandler.cpp

moc_importtab.o: src/presentation/frontends/qtfrontend/moc_importtab.cpp  src/presentation/frontends/qtfrontend/importtab.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_importtab.o src/presentation/frontends/qtfrontend/moc_importtab.cpp

moc_framebar.o: src/presentation/frontends/qtfrontend/framebar/moc_framebar.cpp  src/presentation/frontends/qtfrontend/framebar/framebar.h src/config.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/foundation/logger.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_framebar.o src/presentation/frontends/qtfrontend/framebar/moc_framebar.cpp

moc_scenearrowbutton.o: src/presentation/frontends/qtfrontend/framebar/moc_scenearrowbutton.cpp  src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scenearrowbutton.o src/presentation/frontends/qtfrontend/framebar/moc_scenearrowbutton.cpp

moc_scenethumbview.o: src/presentation/frontends/qtfrontend/framebar/moc_scenethumbview.cpp  src/presentation/frontends/qtfrontend/framebar/scenethumbview.h src/presentation/frontends/qtfrontend/framebar/thumbview.h \
		src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.h \
		src/presentation/frontends/qtfrontend/framebar/framebar.h \
		src/config.h \
		src/presentation/observer.h \
		src/domain/animation/animationmodel.h \
		src/domain/animation/frame.h \
		src/presentation/frontends/qtfrontend/framepreferencesmenu.h \
		src/foundation/logger.h \
		src/presentation/frontends/frontend.h \
		src/technical/audio/audioformat.h \
		src/technical/audio/audiodriver.h \
		src/technical/video/videoencoder.h \
		src/presentation/frontends/qtfrontend/menuframe.h \
		src/application/soundhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scenethumbview.o src/presentation/frontends/qtfrontend/framebar/moc_scenethumbview.cpp

moc_exporttab.o: src/presentation/frontends/qtfrontend/moc_exporttab.cpp  src/presentation/frontends/qtfrontend/exporttab.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exporttab.o src/presentation/frontends/qtfrontend/moc_exporttab.cpp

moc_externalchangemonitor.o: src/application/moc_externalchangemonitor.cpp  src/application/externalchangemonitor.h src/config.h \
		src/foundation/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_externalchangemonitor.o src/application/moc_externalchangemonitor.cpp

moc_helpwindow.o: src/presentation/frontends/qtfrontend/moc_helpwindow.cpp  src/presentation/frontends/qtfrontend/helpwindow.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helpwindow.o src/presentation/frontends/qtfrontend/moc_helpwindow.cpp

src/presentation/frontends/qtfrontend/moc_mainwindowgui.cpp: $(MOC) src/presentation/frontends/qtfrontend/mainwindowgui.h
	$(MOC) src/presentation/frontends/qtfrontend/mainwindowgui.h -o src/presentation/frontends/qtfrontend/moc_mainwindowgui.cpp

src/presentation/frontends/qtfrontend/moc_qtfrontend.cpp: $(MOC) src/presentation/frontends/qtfrontend/qtfrontend.h
	$(MOC) src/presentation/frontends/qtfrontend/qtfrontend.h -o src/presentation/frontends/qtfrontend/moc_qtfrontend.cpp

src/application/moc_runanimationhandler.cpp: $(MOC) src/application/runanimationhandler.h
	$(MOC) src/application/runanimationhandler.h -o src/application/moc_runanimationhandler.cpp

src/application/moc_camerahandler.cpp: $(MOC) src/application/camerahandler.h
	$(MOC) src/application/camerahandler.h -o src/application/moc_camerahandler.cpp

src/presentation/frontends/qtfrontend/moc_frameview.cpp: $(MOC) src/presentation/frontends/qtfrontend/frameview.h
	$(MOC) src/presentation/frontends/qtfrontend/frameview.h -o src/presentation/frontends/qtfrontend/moc_frameview.cpp

src/presentation/frontends/qtfrontend/moc_flexiblespinbox.cpp: $(MOC) src/presentation/frontends/qtfrontend/flexiblespinbox.h
	$(MOC) src/presentation/frontends/qtfrontend/flexiblespinbox.h -o src/presentation/frontends/qtfrontend/moc_flexiblespinbox.cpp

src/presentation/frontends/qtfrontend/moc_menuframe.cpp: $(MOC) src/presentation/frontends/qtfrontend/menuframe.h
	$(MOC) src/presentation/frontends/qtfrontend/menuframe.h -o src/presentation/frontends/qtfrontend/moc_menuframe.cpp

src/presentation/frontends/qtfrontend/moc_flexiblelineedit.cpp: $(MOC) src/presentation/frontends/qtfrontend/flexiblelineedit.h
	$(MOC) src/presentation/frontends/qtfrontend/flexiblelineedit.h -o src/presentation/frontends/qtfrontend/moc_flexiblelineedit.cpp

src/presentation/frontends/qtfrontend/moc_filedialog.cpp: $(MOC) src/presentation/frontends/qtfrontend/filedialog.h
	$(MOC) src/presentation/frontends/qtfrontend/filedialog.h -o src/presentation/frontends/qtfrontend/moc_filedialog.cpp

src/application/moc_soundhandler.cpp: $(MOC) src/application/soundhandler.h
	$(MOC) src/application/soundhandler.h -o src/application/moc_soundhandler.cpp

src/presentation/frontends/qtfrontend/moc_framepreferencesmenu.cpp: $(MOC) src/presentation/frontends/qtfrontend/framepreferencesmenu.h
	$(MOC) src/presentation/frontends/qtfrontend/framepreferencesmenu.h -o src/presentation/frontends/qtfrontend/moc_framepreferencesmenu.cpp

src/application/moc_editmenuhandler.cpp: $(MOC) src/application/editmenuhandler.h
	$(MOC) src/application/editmenuhandler.h -o src/application/moc_editmenuhandler.cpp

src/presentation/frontends/qtfrontend/moc_videoview.cpp: $(MOC) src/presentation/frontends/qtfrontend/videoview.h
	$(MOC) src/presentation/frontends/qtfrontend/videoview.h -o src/presentation/frontends/qtfrontend/moc_videoview.cpp

src/presentation/frontends/qtfrontend/moc_preferencesmenu.cpp: $(MOC) src/presentation/frontends/qtfrontend/preferencesmenu.h
	$(MOC) src/presentation/frontends/qtfrontend/preferencesmenu.h -o src/presentation/frontends/qtfrontend/moc_preferencesmenu.cpp

src/application/moc_modelhandler.cpp: $(MOC) src/application/modelhandler.h
	$(MOC) src/application/modelhandler.h -o src/application/moc_modelhandler.cpp

src/presentation/frontends/qtfrontend/moc_toolsmenu.cpp: $(MOC) src/presentation/frontends/qtfrontend/toolsmenu.h
	$(MOC) src/presentation/frontends/qtfrontend/toolsmenu.h -o src/presentation/frontends/qtfrontend/moc_toolsmenu.cpp

src/application/moc_languagehandler.cpp: $(MOC) src/application/languagehandler.h
	$(MOC) src/application/languagehandler.h -o src/application/moc_languagehandler.cpp

src/presentation/frontends/qtfrontend/moc_importtab.cpp: $(MOC) src/presentation/frontends/qtfrontend/importtab.h
	$(MOC) src/presentation/frontends/qtfrontend/importtab.h -o src/presentation/frontends/qtfrontend/moc_importtab.cpp

src/presentation/frontends/qtfrontend/framebar/moc_framebar.cpp: $(MOC) src/presentation/frontends/qtfrontend/framebar/framebar.h
	$(MOC) src/presentation/frontends/qtfrontend/framebar/framebar.h -o src/presentation/frontends/qtfrontend/framebar/moc_framebar.cpp

src/presentation/frontends/qtfrontend/framebar/moc_scenearrowbutton.cpp: $(MOC) src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.h
	$(MOC) src/presentation/frontends/qtfrontend/framebar/scenearrowbutton.h -o src/presentation/frontends/qtfrontend/framebar/moc_scenearrowbutton.cpp

src/presentation/frontends/qtfrontend/framebar/moc_scenethumbview.cpp: $(MOC) src/presentation/frontends/qtfrontend/framebar/scenethumbview.h
	$(MOC) src/presentation/frontends/qtfrontend/framebar/scenethumbview.h -o src/presentation/frontends/qtfrontend/framebar/moc_scenethumbview.cpp

src/presentation/frontends/qtfrontend/moc_exporttab.cpp: $(MOC) src/presentation/frontends/qtfrontend/exporttab.h
	$(MOC) src/presentation/frontends/qtfrontend/exporttab.h -o src/presentation/frontends/qtfrontend/moc_exporttab.cpp

src/application/moc_externalchangemonitor.cpp: $(MOC) src/application/externalchangemonitor.h
	$(MOC) src/application/externalchangemonitor.h -o src/application/moc_externalchangemonitor.cpp

src/presentation/frontends/qtfrontend/moc_helpwindow.cpp: $(MOC) src/presentation/frontends/qtfrontend/helpwindow.h
	$(MOC) src/presentation/frontends/qtfrontend/helpwindow.h -o src/presentation/frontends/qtfrontend/moc_helpwindow.cpp

####### Install

install_target: all 
	@$(CHK_DIR_EXISTS) "$(INSTALL_ROOT)debian/stopmotion/usr/bin/" || $(MKDIR) "$(INSTALL_ROOT)debian/stopmotion/usr/bin/"
	-$(INSTALL_FILE) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)debian/stopmotion/usr/bin/$(QMAKE_TARGET)"
	-strip "$(INSTALL_ROOT)debian/stopmotion/usr/bin/$(QMAKE_TARGET)"

uninstall_target: 
	-$(DEL_FILE) "$(INSTALL_ROOT)debian/stopmotion/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) "$(INSTALL_ROOT)debian/stopmotion/usr/bin/"


install: install_target  

uninstall: uninstall_target  

