<!DOCTYPE TS><TS>
<context>
    <name>CameraHandler</name>
    <message>
        <source>Camera &amp;off</source>
        <translation type="obsolete">&amp;Kamera av</translation>
    </message>
    <message>
        <source>Camera &amp;on</source>
        <translation type="obsolete">&amp;Kamera på</translation>
    </message>
</context>
<context>
    <name>ExportTab</name>
    <message>
        <source>Active</source>
        <translation type="unfinished">Aktiv</translation>
    </message>
    <message>
        <source>Name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Description</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Add</source>
        <translation type="unfinished">&amp;Legg til</translation>
    </message>
    <message>
        <source>&amp;Remove</source>
        <translation type="unfinished">&amp;Fjern</translation>
    </message>
    <message>
        <source>&amp;Edit</source>
        <translation type="unfinished">&amp;Rediger</translation>
    </message>
    <message>
        <source>Encoder settings</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Do you want to be asked for an output file everytime you choose to export?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Yes</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>No</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Set default output file:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Browse</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Start encoder:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Stop encoder:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Choose output file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;p&gt;Below you can set which program/process stopmotion should use for encoding the currently active project to a video file.&lt;/p&gt;&lt;p&gt;You can use $IMAGEPATH to represent the image path (absolute path to the directory where the images can be found). You should always use &lt;b&gt;$VIDEOFILE&lt;/b&gt; to represent the output file (the videofile generated by the encoder) in the &lt;b&gt;command line&lt;/b&gt;. This is independent of how you decides to select it (select it for each export or have a default file).&lt;br&gt;&lt;/p&gt;&lt;p&gt; Example with mencoder (converting jpg to mpeg1): &lt;br&gt;mencoder mf://$IMAGEPATH/*.jpg -mf w=640:h=480:fps=12:type=jpg -ovc lavc -lavcopts vcodec=mpeg1video -oac copy -o $VIDEOFILE &lt;br&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>FileDialog</name>
    <message>
        <source>Go to home directory</source>
        <translation>Gå til hjemmekatalog</translation>
    </message>
</context>
<context>
    <name>FramePreferencesMenu</name>
    <message>
        <source>Add &amp;sound</source>
        <translation type="unfinished">Legg til &amp;lyd</translation>
    </message>
    <message>
        <source>&amp;Remove Sound</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Change name</source>
        <translation type="unfinished">Skift navn</translation>
    </message>
    <message>
        <source>Sounds:</source>
        <translation type="unfinished">Lyder:</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Add sound&lt;/h4&gt; &lt;p&gt;With this button you can &lt;em&gt;add sounds&lt;/em&gt; to the selected frame.&lt;/p&gt; &lt;p&gt;The sound will begin playing when this frame is shown and play until it is done.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Remove sound&lt;/h4&gt; &lt;p&gt;With this button you can &lt;em&gt;remove&lt;/em&gt; the selected sound from this frame.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Change name&lt;/h4&gt; &lt;p&gt;With this button you can change the name of the selected sound. &lt;BR&gt;The name of the sound has no other effect than making it easier work with the animation.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Sounds&lt;/h4&gt; &lt;p&gt;This lists shows all the sounds connected to this frame.&lt;/p&gt;&lt;p&gt;The sounds will begin playing when this frame is shown and play until they are done.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>FrameView</name>
    <message>
        <source>Warning</source>
        <translation>Advarsel</translation>
    </message>
    <message>
        <source>Grabbing failed. This may happen if you try
to grab from an invalid device. Please check
your grabber settings in the preferences menu.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>You have to define an image grabber to use.
This can be set in the preferences menu.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>HelpWindow</name>
    <message>
        <source>&amp;New Window</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Open File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Print</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Close</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Backward</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Forward</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Home</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Add Bookmark</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;File</source>
        <translation type="unfinished">&amp;Fil</translation>
    </message>
    <message>
        <source>&amp;Go</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>History</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bookmarks</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Backward</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Forward</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Home</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ImportTab</name>
    <message>
        <source>&lt;p&gt;Below you can set which program/process stopmotion should use for grabbing images from the webcam, and displaying video.&lt;br&gt; &lt;br&gt; &lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Active</source>
        <translation type="unfinished">Aktiv</translation>
    </message>
    <message>
        <source>Name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Description</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Add</source>
        <translation type="unfinished">&amp;Legg til</translation>
    </message>
    <message>
        <source>&amp;Remove</source>
        <translation type="unfinished">&amp;Fjern</translation>
    </message>
    <message>
        <source>&amp;Edit</source>
        <translation type="unfinished">&amp;Rediger</translation>
    </message>
    <message>
        <source>Import device settings</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Pre-poll command</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Start deamon</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Stop deamon</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>LanguageHandler</name>
    <message>
        <source>&amp;English</source>
        <translation type="obsolete">&amp;Engelsk</translation>
    </message>
    <message>
        <source>&lt;h4&gt;English&lt;/h4&gt; &lt;p&gt;Select this menu options to get the &lt;em&gt;English&lt;/em&gt; translation of the application.&lt;/p&gt;</source>
        <translation type="obsolete">&lt;h4&gt;Engelsk&lt;/h4&gt; &lt;p&gt;Dette menyvalget vil gi deg den engelske oversettingen av programmet.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>&amp;Norwegian</source>
        <translation type="obsolete">&amp;Norsk</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Norwegian&lt;/h4&gt; &lt;p&gt;Select this menu options to get the &lt;em&gt;Norwegian&lt;/em&gt; translation of the application.&lt;/p&gt;</source>
        <translation type="obsolete">&lt;h4&gt;Norsk&lt;/h4&gt; &lt;p&gt;Dette menyvalget vil gi deg den norske oversettingen av programmet.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>English</source>
        <comment>This should be translated to the name of the language you are translating to, in that language. Example: English = Deutsch (Deutsch is &quot;German&quot; in German)</comment>
        <translation>Norsk</translation>
    </message>
    <message>
        <source>English</source>
        <translation type="unfinished">norsk</translation>
    </message>
</context>
<context>
    <name>MainWindowGUI</name>
    <message>
        <source>Ready to rumble ;-)</source>
        <translation>Klar til dyst ;-)</translation>
    </message>
    <message>
        <source>&amp;New</source>
        <translation>&amp;Ny</translation>
    </message>
    <message>
        <source>&amp;Open</source>
        <translation>&amp;Åpne</translation>
    </message>
    <message>
        <source>&amp;Save</source>
        <translation>&amp;Lagre</translation>
    </message>
    <message>
        <source>Save &amp;As</source>
        <translation>Lagre &amp;som</translation>
    </message>
    <message>
        <source>Add &amp;Frames</source>
        <translation type="obsolete">Legg til &amp;bilde</translation>
    </message>
    <message>
        <source>&amp;Quit</source>
        <translation>&amp;Avslutt</translation>
    </message>
    <message>
        <source>&amp;File</source>
        <translation>&amp;Fil</translation>
    </message>
    <message>
        <source>&amp;Undo</source>
        <translation>&amp;Angre</translation>
    </message>
    <message>
        <source>Re&amp;do</source>
        <translation>&amp;Gjør om</translation>
    </message>
    <message>
        <source>Cu&amp;t</source>
        <translation>Klipp &amp;ut</translation>
    </message>
    <message>
        <source>&amp;Copy</source>
        <translation>&amp;Kopier</translation>
    </message>
    <message>
        <source>&amp;Paste</source>
        <translation>&amp;Lim inn</translation>
    </message>
    <message>
        <source>&amp;Go to frame</source>
        <translation>&amp;Gå til bilde</translation>
    </message>
    <message>
        <source>Prefere&amp;nces</source>
        <translation type="obsolete">&amp;Preferanser</translation>
    </message>
    <message>
        <source>&amp;Edit</source>
        <translation>&amp;Rediger</translation>
    </message>
    <message>
        <source>What&apos;s &amp;This</source>
        <translation>H&amp;va er dette</translation>
    </message>
    <message>
        <source>&amp;About</source>
        <translation>&amp;Om</translation>
    </message>
    <message>
        <source>&amp;Help</source>
        <translation>&amp;Hjelp</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Frame preferences menu&lt;/h4&gt; &lt;p&gt;In this menu you can set preferences for the selected frame/frames, such as &lt;b&gt;subtitles&lt;/b&gt;, &lt;b&gt;sound effects&lt;/b&gt;, etc.&lt;/p&gt;</source>
        <translation>&lt;h4&gt;Bildeinnstillinger&lt;/h4&gt; &lt;p&gt;I denne menyen kan du sette innstillinger for den valgte frame slik som &lt;b&gt;undertekst&lt;/b&gt;, &lt;b&gt;lydeffekter&lt;/b&gt;, etc. &lt;/p&gt;</translation>
    </message>
    <message>
        <source>Add sound</source>
        <translation type="obsolete">Legg til lyd</translation>
    </message>
    <message>
        <source>Remove Sound</source>
        <translation type="obsolete">Fjern lyd</translation>
    </message>
    <message>
        <source>Change name</source>
        <translation type="obsolete">Skift navn</translation>
    </message>
    <message>
        <source>Sounds:</source>
        <translation type="obsolete">Lyder:</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Go to frame menu&lt;/h4&gt; &lt;p&gt;Here you can specify a framenumber and the program will jump to the specified frame&lt;/p&gt; </source>
        <translation>&lt;h4&gt;Gå til bilde-menyen&lt;/h4&gt; &lt;p&gt;I denne menyen kan du angi nummeret til et bilde som programmet skal gå til.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>Go to frame:</source>
        <translation>Gå til frame:</translation>
    </message>
    <message>
        <source>Frame number: 0</source>
        <translation>Frame: 0</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Frame number&lt;/h4&gt;&lt;p&gt;This area displays the numberof the currently selected frame&lt;/p&gt;</source>
        <translation>&lt;h4&gt;Bildenummer&lt;/h4&gt; &lt;p&gt;Dette feltet viser nummeret på det valgte bildet.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>Unsaved changes</source>
        <translation>Ulagrede forandringer</translation>
    </message>
    <message>
        <source>There are unsaved changes. Do you want to save?</source>
        <translation>Det er forandringer som ikke har blitt lagret. Ønsker du å lagre dem nå?</translation>
    </message>
    <message>
        <source>&amp;Yes</source>
        <translation>&amp;Ja</translation>
    </message>
    <message>
        <source>&amp;No</source>
        <translation>&amp;Nei</translation>
    </message>
    <message>
        <source>&lt;p&gt;This is the stopmotion application for creating stopmotion animations.&lt;/p&gt;&lt;p&gt;(c) 2005, Fredrik Berg Kj&#xf8;lstad and Bj&#xf8;rn Erik Nilsen&lt;/p&gt;</source>
        <translation>&lt;p&gt;Dette er Stopmotion-applikasjonen til å lage stop motion-animasjoner. &lt;/p&gt; &lt;p&gt;(c) 2005, Fredrik Berg Kjølstad and Bjørn Erik Nilsen&lt;/p&gt;</translation>
    </message>
    <message>
        <source>Save File</source>
        <translation>Lagre fil</translation>
    </message>
    <message>
        <source>&amp;Thanks To</source>
        <translation>&amp;Takk til</translation>
    </message>
    <message>
        <source>&amp;Licence Agreement</source>
        <translation>&amp;Lisensavtale</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Open&lt;/h4&gt; &lt;p&gt;&lt;em&gt;Opens&lt;/em&gt; a Stopmotion project file.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Undo&lt;/h4&gt; &lt;p&gt;&lt;em&gt;Undoes&lt;/em&gt; your last operation. You can press undo several time to undo earlier operations.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Redo&lt;/h4&gt; &lt;p&gt;&lt;em&gt;Redoes&lt;/em&gt; your last operation. You can press redo several times to redo several operations.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Cut&lt;/h4&gt; &lt;p&gt;&lt;em&gt;Cuts&lt;/em&gt; the selected frames out of the animation and adds them to the clipboard so that you can paste them in somewhere else.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Copy&lt;/h4&gt; &lt;p&gt;&lt;em&gt;Copies&lt;/em&gt; the selected frames to the clipboard. You can then paste them in another place.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Paste&lt;/h4&gt; &lt;p&gt;&lt;em&gt;Pastes&lt;/em&gt; the frames which are currently in the clipboard into the selected location.&lt;/p&gt; &lt;p&gt;You can copy/cut images from another programs and then use this option to paste them into this animation.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;What&apos;s This&lt;/h4&gt; &lt;p&gt;This will give you a WhatsThis mouse cursor which can be used to bring up helpful information like this.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;About&lt;/h4&gt; &lt;p&gt;This will display a small information box where you can read general information as well as the names of the developers behind this excellent piece of software.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;FrameBar&lt;/h4&gt; &lt;p&gt;In this area you can see the frames and scenes in the animations and build the animation by moving the them around.&lt;/p&gt;&lt;p&gt;You can switch to the next and the previous frame using the &lt;b&gt;arrow buttons&lt;/b&gt; or &lt;b&gt;x&lt;/b&gt; and &lt;b&gt;z&lt;/b&gt;&lt;/p&gt; </source>
        <translation type="unfinished">fsfds</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Tool menu&lt;/h4&gt; &lt;p&gt;This is the tool menu where most of the buttons and widgets you will need when working on stop motion animations are located.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Add &amp;sound</source>
        <translation type="obsolete">Legg til &amp;lyd</translation>
    </message>
    <message>
        <source>&lt;h4&gt;FrameView&lt;/h4&gt;&lt;p&gt; In this area you can see the selected frame. You can also play animations in this window by pressing the &lt;b&gt;Play&lt;/b&gt; button.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>A&amp;uthors</source>
        <translation>&amp;Forfattere</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Quit&lt;/h4&gt; &lt;p&gt;&lt;em&gt;Quits&lt;/em&gt; the program.&lt;/p&gt;</source>
        <translation>&lt;h4&gt;Avslutt&lt;/h4&gt; &lt;p&gt;&lt;em&gt;Avsutter&lt;/em&gt; programmet.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Go to frame&lt;/h4&gt; &lt;p&gt;This will bring up a popup-menu at the bottom where you can choose a frame you want to &lt;em&gt;go to&lt;/em&gt;.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;English</source>
        <translation type="obsolete">&amp;Engelsk</translation>
    </message>
    <message>
        <source>&lt;h4&gt;English&lt;/h4&gt; &lt;p&gt;Select this menu options to get the &lt;em&gt;English&lt;/em&gt; translation of the application.&lt;/p&gt;</source>
        <translation type="obsolete">&lt;h4&gt;Engelsk&lt;/h4&gt; &lt;p&gt;Dette menyvalget vil gi deg den engelske oversettingen av programmet.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>&amp;Norwegian</source>
        <translation type="obsolete">&amp;Norsk</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Norwegian&lt;/h4&gt; &lt;p&gt;Select this menu options to get the &lt;em&gt;Norwegian&lt;/em&gt; translation of the application.&lt;/p&gt;</source>
        <translation type="obsolete">&lt;h4&gt;Norsk&lt;/h4&gt; &lt;p&gt;Dette menyvalget vil gi deg den norske oversettingen av programmet.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>&amp;Languages</source>
        <translation>&amp;Språk</translation>
    </message>
    <message>
        <source>&amp;Settings</source>
        <translation>I&amp;nnstillinger</translation>
    </message>
    <message>
        <source>Disable sound</source>
        <translation type="obsolete">Skru av lyd</translation>
    </message>
    <message>
        <source>Video</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Export</source>
        <translation>&amp;Eksport</translation>
    </message>
    <message>
        <source>&lt;h4&gt;New&lt;/h4&gt; &lt;p&gt;Creates a &lt;em&gt;new&lt;/em&gt; project.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Save&lt;/h4&gt; &lt;p&gt;&lt;em&gt;Saves&lt;/em&gt; the current animation as a Stopmotion project file. &lt;BR&gt;If this project has been saved before it will automaticly be saved to the previously selected file.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Save As&lt;/h4&gt; &lt;p&gt;&lt;em&gt;Saves&lt;/em&gt; the current animation as a Stopmotion project file.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Video&lt;/h4&gt; &lt;p&gt;Exports the current project as &lt;em&gt;video&lt;/em&gt;.&lt;/p&gt;You will be given a wizard to guide you.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Cinerella&lt;/h4&gt; &lt;p&gt;Exports the current animation as a &lt;em&gt;Cinerella&lt;/em&gt; project.&lt;/p&gt;You will be given a wizard to guide you.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Cinelerra</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Configure Stopmotion</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Open &amp;Recent</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>New project</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Open project</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Save project</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Save project As</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Quit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Undo</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Redo</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Cut</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Copy</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Paste</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Go to frame</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Configure Stopmotion&lt;/h4&gt; &lt;p&gt;This will opens a window where you can &lt;em&gt;configure&lt;/em&gt; Stopmotion with various input and output devices.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Configure Stopmotion</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>What&apos;s This</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>About</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Warning</source>
        <translation type="unfinished">Advarsel</translation>
    </message>
    <message>
        <source>Cannot find any registered encoder to be used for
video export. This can be setted in the preferences
menu. Export to video will not be possible until you
have setted an encoder to use. Do you want to set it now?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Export to video file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>The registered encoder is not valid. Do you want
to check your settings in the preferences menu?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Export to file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;p&gt;&lt;b&gt;Coordinating&lt;/b&gt;&lt;br&gt;Herman Robak &amp;lt;herman@skolelinux.no&amp;gt;&lt;br&gt;&#xd8;yvind Kol&#xe5;s &amp;lt;pippin@gimp.org&amp;gt;&lt;/p&gt;&lt;p&gt;&lt;b&gt;Testing&lt;/b&gt;&lt;br&gt;Tore Sinding Bekkedal &amp;lt;toresbe@ifi.uio.no&amp;gt;&lt;br&gt;Finn Arne Johansen &amp;lt;faj@bzz.no&amp;gt;&lt;br&gt;Halvor Borgen &amp;lt;halvor.borgen@hig.no&amp;gt;&lt;br&gt;Bj&#xf8;rn Are Hansen &amp;lt;post@bahansen.net&amp;gt;&lt;br&gt;John Steinar Bild&#xf8;y &amp;lt;johnsbil@haldenfriskole.no&amp;gt;&lt;br&gt;Ole-Anders Andreassen &amp;lt;ole-anders.andreassen@sunndal.kommune.no&amp;gt;&lt;br&gt;&lt;/p&gt;&lt;p&gt;&lt;b&gt;Translation&lt;/b&gt;&lt;br&gt;&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Help&lt;/h4&gt; &lt;p&gt;This button will bring up a dialog with the Stopmotion manual&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Help</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;p&gt;&lt;b&gt;Main developers&lt;/b&gt;&lt;br&gt;Fredrik Berg Kj&#xf8;lstad &amp;lt;fredrikbk@hotmail.com&amp;gt;&lt;br&gt;Bj&#xf8;rn Erik Nilsen &amp;lt;bjoern.nilsen@bjoernen.com&amp;gt;&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Stopmotion User Manual</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ModelHandler</name>
    <message>
        <source>Choose frames to add</source>
        <translation>Velg frames å legge til</translation>
    </message>
    <message>
        <source>Removed the selected frame</source>
        <translation>Fjernet den valgte frame</translation>
    </message>
</context>
<context>
    <name>PreferencesMenu</name>
    <message>
        <source>&lt;p&gt;Below you can set which program/process stopmotion should use for grabing images from the webcam, and displaying video.&lt;br&gt; &lt;br&gt; You can also add new programs, just make sure the image is saved with the path and filename &lt;b&gt;.stopmotion/capturedfile.png&lt;/b&gt; &lt;/p&gt;</source>
        <translation type="obsolete">&lt;p&gt;Nedenfor kan du angi hvilket program/prosess som Stopmotion skal bruke for å ta bilder fra webkameraer, etc. &lt;br&gt;&lt;br&gt;Du kan også legge til nye programmer. Bare sørg for at bildet blir lagret med stien og filnavnet &lt;b&gt;$HOME/.stopmotion/capturedfile.png&lt;/b&gt; &lt;/p&gt;</translation>
    </message>
    <message>
        <source>&amp;Add</source>
        <translation type="obsolete">&amp;Legg til</translation>
    </message>
    <message>
        <source>Video &amp;Import</source>
        <translation>Video &amp;import</translation>
    </message>
    <message>
        <source>&lt;p&gt;Video Export&lt;/p&gt;</source>
        <translation type="obsolete">&lt;p&gt;Video eksport&lt;/p&gt;</translation>
    </message>
    <message>
        <source>Video &amp;Export</source>
        <translation>Video &amp;export</translation>
    </message>
    <message>
        <source>Active</source>
        <translation type="obsolete">Aktiv</translation>
    </message>
    <message>
        <source>Command line option</source>
        <translation type="obsolete">Kommandolinje-opsjon</translation>
    </message>
    <message>
        <source>&lt;p&gt;Below you can set which program/process stopmotion should use for grabbing images from the webcam, and displaying video.&lt;br&gt; &lt;br&gt; You can also add new programs, just make sure the command line is written with file path being &lt;b&gt;&amp;lt;DEFAULTPATH&amp;gt;&lt;/b&gt;&lt;/p&gt;</source>
        <translation type="obsolete">&lt;p&gt;Nedenfor kan du angi hvilket program/prosess som Stopmotion skal bruke for å ta bilder fra webkameraer, etc. &lt;br&gt;&lt;br&gt;Du kan også legge til nye programmer. Bare sørg for at kommandolinjen blir skrevet med filstien: &lt;b&gt;&amp;lt;DEFAULTPATH&amp;gt;&lt;/b&gt;&lt;/p&gt;</translation>
    </message>
    <message>
        <source>&amp;Remove</source>
        <translation type="obsolete">&amp;Fjern</translation>
    </message>
</context>
<context>
    <name>QtFrontend</name>
    <message>
        <source>Warning</source>
        <translation>Advarsel</translation>
    </message>
    <message>
        <source>Fatal</source>
        <translation>Fatal feil</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Progress</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>vgrabbj VGA singleshot</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>vgrabbj VGA deamon</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Starts vgrabbj as a deamon. Pretty fast.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Question</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;Yes</source>
        <translation type="unfinished">&amp;Ja</translation>
    </message>
    <message>
        <source>&amp;No</source>
        <translation type="unfinished">&amp;Nei</translation>
    </message>
    <message>
        <source>The simplest setting. Fairly slow</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Exports from jpeg images to mpeg1 video</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>mencoder mf://$IMAGEPATH/*.jpg -mf w=640:h=480:fps=12:type=jpg -ovc lavc -lavcopts vcodec=mpeg1video -oac copy -o $VIDEOFILE</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source></source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>RunAnimationHandler</name>
    <message>
        <source>Running animation</source>
        <translation>Kjører animasjonen</translation>
    </message>
</context>
<context>
    <name>SoundHandler</name>
    <message>
        <source>Sounds (*.ogg)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Sound name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Enter the name of the sound:</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ToolsMenu</name>
    <message>
        <source>&amp;Add Frames</source>
        <translation type="obsolete">&amp;Legg til bilder</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Add Frames&lt;/h4&gt; &lt;p&gt;Click on this button to &lt;em&gt;add&lt;/em&gt; frames to the animation.&lt;/p&gt;</source>
        <translation type="obsolete">&lt;h4&gt;Legg til bilder&lt;/h4&gt; &lt;p&gt;Med denne knappen kan du &lt;em&gt;legge til&lt;/em&gt; bilder i animasjonen.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>&amp;Remove Selection</source>
        <translation type="obsolete">&amp;Fjern valgte</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Remove Selection&lt;/h4&gt; &lt;p&gt;Click this button to &lt;em&gt;remove&lt;/em&gt; the selected frames from the animation.&lt;/p&gt;</source>
        <translation type="obsolete">&lt;h4&gt;Fjern valgte bilder&lt;/h4&gt; &lt;p&gt;Trykk på denne knappen for å &lt;em&gt;fjerne&lt;/em&gt; de valgte bildene fra animasjonen.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>New &amp;Scene</source>
        <translation type="obsolete">Ny &amp;scene</translation>
    </message>
    <message>
        <source>&lt;h4&gt;New Scene&lt;/h4&gt; &lt;p&gt;Click this button to &lt;em&gt;create&lt;/em&gt; a new &lt;em&gt;scene&lt;/em&gt; to the animation.&lt;/p&gt;</source>
        <translation type="obsolete">&lt;h4&gt;Ny Scene&lt;/h4&gt; &lt;p&gt;Med denne knappen kan du lage en ny &lt;em&gt;scene/em&gt; som legges til animasjonen&lt;/p&gt;</translation>
    </message>
    <message>
        <source>Re&amp;move Scene</source>
        <translation type="obsolete">&amp;Fjern scene</translation>
    </message>
    <message>
        <source>Camera &amp;on</source>
        <translation type="obsolete">&amp;Kamera på</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Toggle camera on/off&lt;/h4&gt; &lt;p&gt;Click this button to toggle the camera on and off&lt;/p&gt;</source>
        <translation type="obsolete">&lt;h4&gt;Skru kamerae av/på&lt;/h4&gt; &lt;p&gt;Med denne knappen kan du skru kameraet av og på&lt;/p&gt;</translation>
    </message>
    <message>
        <source>&amp;Capture Frame</source>
        <translation type="obsolete">&amp;Ta bilde</translation>
    </message>
    <message>
        <source>&lt;h4&gt;Capture Frame&lt;/h4&gt; &lt;p&gt;Click on this button to &lt;em&gt;capture&lt;/em&gt; a frame from the camera an put it in the animation&lt;/p&gt;</source>
        <translation type="obsolete">&lt;h4&gt;Ta bilde&lt;/h4&gt; &lt;p&gt;Trykk på denne knappen for å ta et bilde fra kameraet ditt og legge det til animasjonen&lt;/p&gt;</translation>
    </message>
    <message>
        <source>Number of mixes:</source>
        <translation type="obsolete">Antall bilder mikset på:</translation>
    </message>
    <message>
        <source>FPS chooser</source>
        <translation>FPS-velger</translation>
    </message>
    <message>
        <source>&lt;h4&gt;FPS chooser&lt;/h4&gt; &lt;p&gt;By changing the value in this chooser you set which speed the animation in the &lt;b&gt;FrameView&lt;/b&gt; should run at.&lt;/p&gt; &lt;p&gt;To start an animation press the &lt;b&gt;Run Animation&lt;/b&gt; button.&lt;/p&gt;</source>
        <translation>&lt;h4&gt;FPS-velger&lt;/h4&gt; &lt;p&gt;Ved å forandre verdien i dette feltet kan du bestemme hastigheten (i bilder per sekund) animasjonen skal kjøre i.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>Mix</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Diff</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Number of images:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Playback</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Add Frames (CTRL+F)&lt;/h4&gt; &lt;p&gt;Click on this button to &lt;em&gt;add&lt;/em&gt; frames to the animation.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Remove Selection (Delete)&lt;/h4&gt; &lt;p&gt;Click this button to &lt;em&gt;remove&lt;/em&gt; the selected frames from the animation.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;New Scene (CTRL+E)&lt;/h4&gt; &lt;p&gt;Click this button to &lt;em&gt;create&lt;/em&gt; a new &lt;em&gt;scene&lt;/em&gt; to the animation.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Remove Scene (SHIFT+Delete)&lt;/h4&gt; &lt;p&gt;Click this button to &lt;em&gt;remove&lt;/em&gt; the selected scene from the animation.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Toggle camera on/off (C)&lt;/h4&gt; &lt;p&gt;Click this button to toggle the camera on and off&lt;/p&gt; </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Capture Frame (Space)&lt;/h4&gt; &lt;p&gt;Click on this button to &lt;em&gt;capture&lt;/em&gt; a frame from the camera an put it in the animation&lt;/p&gt; &lt;p&gt; This can also be done by pressing the &lt;b&gt;Space key&lt;/b&gt;&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Number of images&lt;/h4&gt; &lt;p&gt;By changing the value in this slidebar you can specify how many images backwards in the animation which should be mixed on top of the camera or if you are in playback mode: how many images to play. &lt;/p&gt; &lt;p&gt;By mixing the previous image(s) onto the camera you can more easily see how the next shot will be in relation to the other, therby making a smoother stop motion animation!&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Play animation (K, P)&lt;/h4&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Stop animation (K, P)&lt;/h4&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Previous frame (J, Left)&lt;/h4&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Next frame (L, Right)&lt;/h4&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Previous scene (I)&lt;/h4&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Next scene (O)&lt;/h4&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;h4&gt;Loop animation (CTRL+L)&lt;/h4&gt; &lt;p&gt;With this button you can set whether you want the animation to play to the end, or to loop indefinetly.&lt;/p&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Notice</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Playback only currently works when running the grabber 
as a deamon. Go to the preferences menu (CTRL+P) to switch 
to running the image grabbing as a deamon.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
